require:
  - rubocop-rails
  - rubocop-graphql


AllCops:
  NewCops: enable

GraphQL/FieldDescription:
  Enabled: false

GraphQL/ObjectDescription:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false
